### PR TITLE
Cross Origin check utility and implementation

### PR DESCRIPTION
**Pull request by DanielBailey-web**
Added a utility that is able to check for cross origin using regex. 

Sets crossOrigin on image to true if it is a cross origin resource.

(fixes a cross-origin "this action is unsafe" error when using images from other websites or api's)

### CODE REVIEW

**Comment by giacomocerquone** [comment]
@DanielBailey-web
Hi 👋  sorry for the waiting and thank you so much for the contributions.

One question, is the regex necessary? Shouldn't be enough to use crossorigin=true and let the browser figure out if the img comes from a cross origin source or not?

**Comment by giacomocerquone** [comment]
any news? @DanielBailey-web

**Comment by DanielBailey-web** [comment]
@giacomocerquone Sorry about the delay, I stopped working on the project that we needed this on. 

It looks like it really should be checked to make sure the the source is cross-origin or it could create some issues with displaying the image. 

See my question I made on [stackoverflow](https://stackoverflow.com/questions/71686596/is-it-okay-to-mark-image-crossorigin-as-anonymous-even-when-it-is-not) and the accepted answer.

**Comment by DanielBailey-web** [comment]
I changed true to anonymous, even though true worked, [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) documentation says to use the string anonymous.

**Review by sagar-vaghela97 — APPROVED** [review]

**Comment by giacomocerquone** [comment]
makes sense thanks

**Comment by giacomocerquone** [comment]
just released version 0.2.2

**Pull request merged**
